name: Bedrock Agent Review (runner)

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: "PR number to analyze"
        required: true
        type: string

permissions:
  id-token: write
  contents: read
  pull-requests: write
  issues: write

env:
  AWS_REGION: "ap-northeast-1"

jobs:
  analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout PR head
        uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ inputs.pr_number }}/head
          fetch-depth: 0 # Fetch all history for diff analysis

      - name: Assume AWS Role using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::649844050696:role/isd1-lab-iamrole-github-actions-deploy
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Run Bedrock Analysis
        uses: severity1/custom-amazon-bedrock-agent-action@v0.10.0
        with:
          agent_id: "HG3FHKX9GY"
          agent_alias_id: "Y7IXOPEHZ2"
          # memory_id: 'terraform-expert-memory' # Titan Models are not supported.
          action_prompt: |
            Role: You are a Commander Agent coordinating Frontend Development

            Task: Review the provided JavaScript (.js) and HTML (.html) changes for syntax, security, performance, accessibility, and best practices. Coordinate with Design Agent and Implementation Agent for analysis only. Do not make actual code modifications.

            Process:
            1. Analyze the changes and identify areas for improvement.
            2. Delegate specific tasks to Design Agent for architecture/tactics and Implementation Agent for code execution.
            3. Compile findings into recommendations.
            4. Output a Japanese summary of the analysis and proposed modifications.

            Expected Output Format (in Japanese):
            ### 変更サマリー
            - **ファイル名: (行番号を含む)**
              - 改善提案: (詳細な内容)

            ### 全体サマリー
            - 司令塔分析結果とエージェント推薦をまとめた日本語サマリー。問題がなければ「問題ありません」とする。
          # ignore_patterns: "**/*.md,docs/**,.github/**"
          debug: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
