name: Bedrock Agent Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  id-token: write
  contents: read
  pull-requests: write
  issues: write

env:
  AWS_REGION: "ap-northeast-1"

jobs:
  analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout PR head
        uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/head
          fetch-depth: 0

      - name: Assume AWS Role using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::649844050696:role/isd1-lab-iamrole-github-actions-deploy
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Run Bedrock Analysis
        uses: severity1/custom-amazon-bedrock-agent-action@v0.10.0
        with:
          agent_id: "HG3FHKX9GY"
          agent_alias_id: "Y7IXOPEHZ2"
          action_prompt: |
            役割: あなたはフロントエンド開発の司令塔エージェントです。次の2つの専門エージェントを調整してPR差分をレビューしてください。
            - 設計エージェント: アーキテクチャ/設計、UI/UX、アクセシビリティ、セキュリティ、パフォーマンス（ロード戦略・画像最適化・キャッシュ・バンドルサイズ）、依存関係、テスト観点を担当。
            - 実装エージェント: コード品質（可読性・命名・重複排除）、潜在バグ、アンチパターン、非同期処理/エラーハンドリング、イベント/DOM操作、モジュール化、型・Lint/Format、パフォーマンス微調整を担当。

            対象: このPRで変更された JavaScript(.js) と HTML(.html)。差分に基づき、具体的・実行可能な指摘と改善提案を出すこと。

            制約:
            - ここではソースコードの直接修正は行わない（レビューと提案のみ）。
            - 可能であれば該当ファイルの行番号を示す。
            - セキュリティ/アクセシビリティ/パフォーマンスは優先度高で確認する。

            出力要件（日本語）:
            ### 設計レビュー（Design Agent）
            - 観点ごとの所見と改善提案（必要なら根拠やリスクも）

            ### 実装レビュー（Implementation Agent）
            - 観点ごとの所見と改善提案（具体的なコード変更案の概要）

            ### 変更サマリー（ファイル別）
            - **ファイル名:（必要なら行番号）**
              - 改善提案:（短く具体的に。理由/効果/注意点）

            ### 優先度と次アクション
            - 高/中/低の優先度付けと推奨手順

            ### 全体サマリー
            - 総評（問題がなければ「問題ありません」）。

            ### Issue 用メタデータ（自動改善フロー連携）
            次のフォーマットで記載。Issue本文にそのまま貼ること。
            ```improve-meta
            pr_number: ${{ github.event.pull_request.number }}
            pr_url: ${{ github.event.pull_request.html_url }}
            head_ref: ${{ github.event.pull_request.head.ref }}
            base_ref: ${{ github.event.pull_request.base.ref }}
            same_repo: true
            ```
          debug: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
